### ISSUE TITLE
internal compiler error

### ISSUE THREAD

**Issue by vfoltsgt** [vladfolts/oberonjs#51]
adva> Подскажите, пожалуйста, на что ругается (знаю, что-то не так с методом push)

Код: [Выделить]
MODULE vscodeOber;

    IMPORT JS;

    TYPE
        
        AnyOb = RECORD END;
        Any* = POINTER TO AnyOb;
        
        Disposable* = POINTER TO RECORD (AnyOb) 
            PROCEDURE push* (disposable: Disposable)
        END;

    VAR
    
    PROCEDURE Disposable.push* (disp: Disposable);
    BEGIN
    END Disposable.push;

BEGIN

END vscodeOber.

Ошибка:
Код: [Выделить]
TypeError: internal compiler error while parsing line 12:         END;
Cannot read property 'exported' of undefined
    at checkMethodExport (C:\git\adva\vsc_oberon\oberonjs\js\EberonContextType.js:85:29)
    at Record.handleMessage (C:\git\adva\vsc_oberon\oberonjs\js\EberonContextType.js:101:4)
    at FieldList.Node.handleMessage (C:\git\adva\vsc_oberon\oberonjs\js\ContextHierarchy.js:49:22)
    at MethodHeading.Node.handleMessage (C:\git\adva\vsc_oberon\oberonjs\js\ContextHierarchy.js:49:22)
    at MethodHeading.endParse (C:\git\adva\vsc_oberon\oberonjs\js\EberonContextType.js:184:19)
    at C:\git\adva\vsc_oberon\oberonjs\parser.js:101:19
    at C:\git\adva\vsc_oberon\oberonjs\parser.js:51:8
    at C:\git\adva\vsc_oberon\oberonjs\parser.js:98:8
    at C:\git\adva\vsc_oberon\oberonjs\parser.js:36:9
    at C:\git\adva\vsc_oberon\oberonjs\parser.js:36:9
The terminal process terminated with exit code: 1

**Comment by iadenisov** [comment]
А разве это нормальный код? Идентификаторы процедур не могут содержать точку.

**Comment by vladfolts** [comment]
Да, проблема в том, что он должен сообщать нормальную ошибку, а не internal compiler error.
Здесь используется Eberon расширение - точка указывает, что это связанная процедура.
Компилятор, видимо, пытается ругаться на сетку экспорта (*), ее там не должно быть, но что-то пошло не так и компилтятор падает.

**Comment by vladfolts** [comment]
I decided to forbid methods declaration (Eberon extension) for `POINTER TO RECORD` types. Supporting this would open new questions like what is the type of `SELF` in this case and maybe others.
